[package]
name = "warp_subscriptions"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# todo#433: add subscriptions example dependencies
env_logger = "0.6.2"
log = "0.4.8"
futures = { version = "=0.3.4" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2", features = ["full"] }
warp = "0.2.1"

juniper_codegen = { path = "../../juniper_codegen", features = ["async"] }
juniper = { path = "../../juniper", features = ["async"] }
juniper_warp = { path = "../../juniper_warp", features = ["async"] }

#juniper_codegen = { git = "https://github.com/graphql-rust/juniper", branch = "async-await", features = ["async"] }
#juniper = { git = "https://github.com/graphql-rust/juniper", branch = "async-await", features = ["async"] }
#juniper_warp = { git = "https://github.com/graphql-rust/juniper", branch = "async-await", features = ["async"] }